# Generated by Django 4.2 on 2024-05-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0014_alter_exercise_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='static',
            field=models.BooleanField(default=False),
        ),
    ]
