# Generated by Django 4.2 on 2024-05-10 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0015_exercise_static'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='pre_requisit_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'static': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_requisits_to_exercises', to='moves.exercise'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='pre_requisits',
            field=models.ForeignKey(blank=True, limit_choices_to={'static': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_requisits_exercises', to='moves.exercise'),
        ),
    ]
