# Generated by Django 4.2 on 2024-05-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0016_exercise_pre_requisit_to_exercise_pre_requisits'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exercise_images/'),
        ),
    ]
