# Generated by Django 4.2 on 2024-05-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0018_exercise_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, limit_choices_to={'static': True}, related_name='leads_to', to='moves.exercise'),
        ),
    ]
