# Generated by Django 4.2 on 2024-05-12 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0019_alter_exercise_prerequisites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='pre_requisit_to',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='pre_requisits',
        ),
    ]
