# Generated by Django 4.2 on 2024-05-12 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moves', '0021_exercise_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExerciseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(choices=[(0, 'Never Tried'), (10, 'Tried in Lines'), (20, 'In Lines (5 seconds+)'), (30, 'With Spotters (5 s+)'), (40, 'In Lines (10 s+)'), (50, 'With Spotters (10 s+)'), (60, 'Out of Lines (10 s+)'), (70, 'Consistently Out of Lines with Multiple People (10 s+)'), (80, 'Consistently Out of Lines No Steps (10 s+)'), (90, 'Consistently Out of Lines No Steps with Multiple People (10 s+)'), (100, 'Mastered')], default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='moves.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'exercise')},
            },
        ),
    ]
